up:
	docker compose up -d

down:
	docker compose down

clean:
	docker compose down --volumes

bash1:
	docker compose exec -it clickhouse-01 bash

client1:
	docker compose exec -it clickhouse-01 clickhouse-client

bash2:
	docker compose exec -it clickhouse-02 bash

client2:
	docker compose exec -it clickhouse-02 clickhouse-client

bash3:
	docker compose exec -it clickhouse-03 bash

client3:
	docker compose exec -it clickhouse-03 clickhouse-client
