server:
  http:
    listen_addr: ':80'
    allowed_networks: ['127.0.0.0/24', '192.168.9.0/24']

users:
  - name: 'admin'
    to_cluster: 'my_cluster'
    to_user: 'default'
    max_concurrent_queries: 100
    max_execution_time: 30s
    requests_per_minute: 10
    # Allow `CORS` requests for `tabix`.
    allow_cors: true
clusters:
  - name: 'my_cluster'
    nodes:
      [
        'clickhouse-01:8123',
        'clickhouse-02:8123',
        'clickhouse-03:8123',
      ]
    users:
      - name: 'default'
